set -g mouse on
set -g history-limit 50000
set -g base-index 1
set -g status-style "bg=colour235,fg=colour250"
set -g status-left "#[fg=colour214] #S "
set -g status-right "%H:%M "
set -g window-size latest
set -g aggressive-resize on
set -sg escape-time 10
set -g default-terminal "tmux-256color"
